# Generated by Django 3.2 on 2024-01-15 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Divisas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.IntegerField()),
                ('simbolo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('ubicacion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('id_divisa', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Monedas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valor', models.IntegerField()),
                ('id_divisa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.divisas')),
            ],
        ),
        migrations.CreateModel(
            name='ProductosCategorizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.categorias')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWeb.productos')),
            ],
            options={
                'unique_together': {('producto', 'categoria')},
            },
        ),
    ]
